
package Frontend;
import backend.MenuItem;
import backend.MenuManager;
import backend.UserManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;


public class AdminPanel extends javax.swing.JFrame {
    private  MenuManager menuManager;
    private UserManager userManager;
    DefaultTableModel model;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminPanel.class.getName());
    public AdminPanel(UserManager userManager,MenuManager menuManager) {
        initComponents();
        this.userManager = userManager;
        this.menuManager = menuManager;
        model = new DefaultTableModel(new String[]{"ID", "Item Name", "Price", "Category"}, 0);
        tblMenu.setModel(model);
        setTitle("N&B Restaurant - Admin Panel");
        setSize(736,1313);
        setLocationRelativeTo(null);  
        menuManager.loadMenuFromDB();
        loadMenu();
        this.dispose();
    }
    
    public void loadMenu() {
        model.setRowCount(0); 
      for (MenuItem item : menuManager.getAllMenuItems()) {
            model.addRow(new Object[]{item.getId(),item.getName(),item.getPrice(),item.getCategory()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        jlabel5 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        txtcategory = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnview = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(736, 1313));
        setSize(new java.awt.Dimension(736, 1313));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("N&B RESTAURANT");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 20, 240, 30);

        jLabel2.setBackground(new java.awt.Color(153, 255, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMIN PANEL");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(268, 65, 125, 25);

        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(204, 102, 0));
        btnAdd.setText("Add item");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(468, 114, 91, 27);

        btnEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(204, 102, 0));
        btnEdit.setText("Edit item");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit);
        btnEdit.setBounds(577, 114, 89, 27);

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(204, 102, 0));
        btnDelete.setText("Delete item");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(475, 181, 105, 27);

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(204, 102, 0));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(598, 181, 72, 27);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Enter Item Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(37, 117, 115, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Enter Price:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 160, 83, 20);

        txtname.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtname);
        txtname.setBounds(181, 110, 246, 37);

        txtprice.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtprice);
        txtprice.setBounds(181, 159, 246, 38);

        jlabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlabel5.setForeground(new java.awt.Color(0, 0, 0));
        jlabel5.setText("Enter Id:");
        getContentPane().add(jlabel5);
        jlabel5.setBounds(44, 221, 76, 20);

        txtid.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtid);
        txtid.setBounds(181, 215, 246, 34);

        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblMenu);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(44, 343, 621, 381);

        txtcategory.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtcategory);
        txtcategory.setBounds(181, 270, 246, 38);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Enter Category:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(44, 278, 101, 20);

        btnview.setBackground(new java.awt.Color(255, 255, 255));
        btnview.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnview.setForeground(new java.awt.Color(204, 102, 0));
        btnview.setText("View Orders:");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });
        getContentPane().add(btnview);
        btnview.setBounds(518, 255, 113, 27);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/admin.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 740, 1313);
        jLabel6.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       String name = txtname.getText();
       String Category = txtcategory.getText();
       double price;
    try {
       price = Double.parseDouble(txtprice.getText());
       } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Enter a valid price!");
       return;
       }
        MenuItem item = new MenuItem(0,name,price,Category);
        menuManager.addMenuToDB(item);
        menuManager.loadMenuFromDB();
        loadMenu(); 
       JOptionPane.showMessageDialog(this,"Item added!");
       txtid.setText("");
       txtname.setText("");
       txtprice.setText("");
       txtcategory.setText(""); 
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
       int id;
       double price;
       String category;
        
        try {
           id = Integer.parseInt(txtid.getText());
       } catch (NumberFormatException e) {
       JOptionPane.showMessageDialog(this, "Enter a valid id!");
       return;
      }
      String name = txtname.getText();
     
      try {
        price = Double.parseDouble(txtprice.getText());
       } catch (NumberFormatException e) {
       JOptionPane.showMessageDialog(this, "Enter a valid price!");
       return;
      }
      
      if (txtname.getText().isEmpty() || txtprice.getText().isEmpty()) {
    JOptionPane.showMessageDialog(this, "All fields are required!");
    return;
     }
     category = txtcategory.getText();
    menuManager.updateMenuInDB(id, name, price, category);
    menuManager.loadMenuFromDB();
    loadMenu();
    JOptionPane.showMessageDialog(this, "Item updated!");
       txtid.setText("");
       txtname.setText("");
       txtprice.setText("");
       txtcategory.setText(""); 
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int id;
        try {
           id = Integer.parseInt(txtid.getText());
       } catch (NumberFormatException e) {
       JOptionPane.showMessageDialog(this, "Enter a valid id!");
       return;
      }
        menuManager.deleteMenuFromDB(id);
        menuManager.loadMenuFromDB();
        loadMenu(); 
        JOptionPane.showMessageDialog(this, "Item Deleted!");
        txtid.setText("");
        txtname.setText("");
        txtprice.setText("");
        txtcategory.setText(""); 
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        JOptionPane.showMessageDialog(null, " Goodbye!! System Executed.");
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
       StringBuilder ordersText = new StringBuilder();

    try {
        BufferedReader br = new BufferedReader(new FileReader("orders.txt"));
        String line;

        while ((line = br.readLine()) != null) {
            ordersText.append(line).append("\n");
        }
        br.close();

    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "No orders found!");
        return;
    }
    
    JTextArea area = new JTextArea(20, 40);
    area.setText(ordersText.toString());
    area.setEditable(false);

    JScrollPane pane = new JScrollPane(area);

    JOptionPane.showMessageDialog(this,pane,"ALL CUSTOMER ORDERS",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnviewActionPerformed

    public static void main(String args[]) {
        UserManager userManager = new UserManager();
        MenuManager menuManager = new MenuManager();
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminPanel(userManager,menuManager).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlabel5;
    private javax.swing.JTable tblMenu;
    private javax.swing.JTextField txtcategory;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables
}
